using PdfSharp.Pdf;
using SharpDocument = PdfSharp.Pdf.PdfDocument;

namespace NetPdf.Creation;

/// <summary>
/// Applies PDF/A-2b structural requirements to a PDFsharp document before saving:
/// a /GTS_PDFA1 output intent with an embedded sRGB ICC profile and PDF version 1.7.
/// The PDF/A identification XMP packet is appended separately after the save (see
/// <c>XmpWriter</c>), because PDFsharp regenerates /Metadata on save.
/// </summary>
internal static class PdfAConformance
{
    /// <summary>Adds the sRGB output intent and sets the document version.</summary>
    internal static void Apply(SharpDocument document)
    {
        document.Version = 17;

        var profile = new PdfDictionary(document);
        profile.Elements["/N"] = new PdfInteger(3);
        document.Internals.AddObject(profile);
        profile.CreateStream(BuildSrgbProfile());

        var intent = new PdfDictionary(document);
        intent.Elements.SetName("/Type", "/OutputIntent");
        intent.Elements.SetName("/S", "/GTS_PDFA1");
        intent.Elements.SetString("/OutputConditionIdentifier", "sRGB IEC61966-2.1");
        intent.Elements.SetString("/Info", "sRGB IEC61966-2.1");
        intent.Elements["/DestOutputProfile"] = profile.Reference;
        document.Internals.AddObject(intent);

        var intents = new PdfArray(document);
        intents.Elements.Add(intent.Reference
            ?? throw new InvalidOperationException("Output intent was not registered."));
        document.Internals.Catalog.Elements["/OutputIntents"] = intents;
    }

    /// <summary>
    /// Builds a minimal ICC v2 display profile describing sRGB: matrix/TRC model with
    /// sRGB primaries (D50-adapted), D65 media white point, and a gamma-2.2 tone curve.
    /// Generated in code, so no external profile file (or its license) is needed.
    /// </summary>
    internal static byte[] BuildSrgbProfile()
    {
        var tags = new List<(string Sig, byte[] Data)>
        {
            ("desc", DescTag("NetPdf sRGB")),
            ("cprt", TextTag("Public domain, generated by NetPdf")),
            // Media white point: D65.
            ("wtpt", XyzTag(0.9505, 1.0000, 1.0891)),
            // sRGB primaries chromatically adapted to D50 (Bradford).
            ("rXYZ", XyzTag(0.4361, 0.2225, 0.0139)),
            ("gXYZ", XyzTag(0.3851, 0.7169, 0.0971)),
            ("bXYZ", XyzTag(0.1431, 0.0606, 0.7141)),
            ("rTRC", GammaCurveTag(2.2)),
            ("gTRC", GammaCurveTag(2.2)),
            ("bTRC", GammaCurveTag(2.2)),
        };

        var headerSize = 128;
        var tagTableSize = 4 + tags.Count * 12;
        var offset = headerSize + tagTableSize;
        var entries = new List<(string Sig, int Offset, int Size)>();
        foreach (var (sig, data) in tags)
        {
            entries.Add((sig, offset, data.Length));
            offset += (data.Length + 3) & ~3; // 4-byte alignment
        }
        var total = offset;

        using var ms = new MemoryStream(total);
        void U32(uint v)
        {
            ms.WriteByte((byte)(v >> 24));
            ms.WriteByte((byte)(v >> 16));
            ms.WriteByte((byte)(v >> 8));
            ms.WriteByte((byte)v);
        }
        void Ascii(string s)
        {
            foreach (var c in s)
                ms.WriteByte((byte)c);
        }

        // Header.
        U32((uint)total);           // profile size
        U32(0);                     // preferred CMM
        U32(0x02100000);            // version 2.1
        Ascii("mntr");              // device class: display
        Ascii("RGB ");              // color space
        Ascii("XYZ ");              // PCS
        U32(2026); U32(0); U32(0);  // creation date (year only; rest zero)
        Ascii("acsp");              // signature
        U32(0);                     // platform
        U32(0);                     // flags
        U32(0);                     // manufacturer
        U32(0);                     // model
        U32(0); U32(0);             // attributes
        U32(0);                     // rendering intent: perceptual
        U32(0x0000F6D6); U32(0x00010000); U32(0x0000D32D); // PCS illuminant: D50
        U32(0);                     // creator
        for (var i = 0; i < 11; i++)
            U32(0);                 // reserved

        // Tag table.
        U32((uint)tags.Count);
        foreach (var (sig, tagOffset, size) in entries)
        {
            Ascii(sig);
            U32((uint)tagOffset);
            U32((uint)size);
        }

        // Tag data, 4-byte aligned.
        foreach (var (_, data) in tags)
        {
            ms.Write(data);
            while (ms.Position % 4 != 0)
                ms.WriteByte(0);
        }
        return ms.ToArray();

        static byte[] XyzTag(double x, double y, double z)
        {
            var data = new byte[20];
            WriteAscii(data, 0, "XYZ ");
            WriteS15Fixed16(data, 8, x);
            WriteS15Fixed16(data, 12, y);
            WriteS15Fixed16(data, 16, z);
            return data;
        }

        static byte[] GammaCurveTag(double gamma)
        {
            var data = new byte[14];
            WriteAscii(data, 0, "curv");
            WriteU32(data, 8, 1); // one entry: gamma as u8Fixed8
            var fixed88 = (ushort)Math.Round(gamma * 256);
            data[12] = (byte)(fixed88 >> 8);
            data[13] = (byte)fixed88;
            return data;
        }

        static byte[] DescTag(string text)
        {
            // desc type: sig, reserved, ASCII count + string (NUL-terminated),
            // Unicode code/count, ScriptCode code/count/data.
            var ascii = text + "\0";
            var data = new byte[12 + ascii.Length + 8 + 3 + 67];
            WriteAscii(data, 0, "desc");
            WriteU32(data, 8, (uint)ascii.Length);
            WriteAscii(data, 12, ascii);
            return data;
        }

        static byte[] TextTag(string text)
        {
            var ascii = text + "\0";
            var data = new byte[8 + ascii.Length];
            WriteAscii(data, 0, "text");
            WriteAscii(data, 8, ascii);
            return data;
        }

        static void WriteAscii(byte[] buffer, int offset, string s)
        {
            for (var i = 0; i < s.Length; i++)
                buffer[offset + i] = (byte)s[i];
        }

        static void WriteU32(byte[] buffer, int offset, uint v)
        {
            buffer[offset] = (byte)(v >> 24);
            buffer[offset + 1] = (byte)(v >> 16);
            buffer[offset + 2] = (byte)(v >> 8);
            buffer[offset + 3] = (byte)v;
        }

        static void WriteS15Fixed16(byte[] buffer, int offset, double v) =>
            WriteU32(buffer, offset, (uint)(int)Math.Round(v * 65536));
    }
}
